# TODO: ADD Infinite playlist loop keybind
#<key> cycle-values loop-playlist yes no ; show-text "${?=loop-playlist==inf:Looping enabled}${?=loop-playlist==no:Looping disabled}"

# ───────────────────────── Keybinds ─────────────────────────
h seek -5
j add volume -2
k add volume 2
l seek 5

a set secondary-sub-visibility yes
A set secondary-sub-visibility no
Ctrl+j cycle secondary-sid
Ctrl+J cycle secondary-sid down

# Toggle dynamic audio normalization (quiet dialogue up, explosions down)
n af toggle @norm:lavfi=[dynaudnorm=f=150:g=15:p=0.9] ; show-text "Normalize: ${?af==:off}${!af==:on}"
