osc=no
fullscreen=no
save-position-on-quit

# LANGUAGES
alang=jpn,jp,eng,en,enUS,en-US
# SUBS
slang=jpn,jp,eng,en,enUS.en-US
#embeddedfonts=yes

# EXTENSIONS
[extension.flac]
fullscreen=no

[extension.mkv]
keep-open

[extension.gif]
loop-file=inf
keep-open

[extension.webm]
loop-file=inf
keep-open
