general {
    lock_cmd         = none
    before_sleep_cmd = none
    after_sleep_cmd  = none
}

listener {
    timeout  = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms("on")'
}
