[completion]
[completion.active]
bg = "#585858"
fg = "#ba8baf"

[completion.border]
fg = "#7cafc2"

[completion.inactive]
fg = "#d8d8d8"

[[filetype.rules]]
fg = "#86c1b9"
mime = "image/*"

[[filetype.rules]]
fg = "#f7ca88"
mime = "video/*"

[[filetype.rules]]
fg = "#f7ca88"
mime = "audio/*"

[[filetype.rules]]
fg = "#ba8baf"
mime = "application/zip"

[[filetype.rules]]
fg = "#ba8baf"
mime = "application/gzip"

[[filetype.rules]]
fg = "#ba8baf"
mime = "application/x-tar"

[[filetype.rules]]
fg = "#ba8baf"
mime = "application/x-bzip"

[[filetype.rules]]
fg = "#ba8baf"
mime = "application/x-bzip2"

[[filetype.rules]]
fg = "#ba8baf"
mime = "application/x-7z-compressed"

[[filetype.rules]]
fg = "#ba8baf"
mime = "application/x-rar"

[[filetype.rules]]
fg = "#ba8baf"
mime = "application/xz"

[[filetype.rules]]
fg = "#a1b56c"
mime = "application/doc"

[[filetype.rules]]
fg = "#a1b56c"
mime = "application/pdf"

[[filetype.rules]]
fg = "#a1b56c"
mime = "application/rtf"

[[filetype.rules]]
fg = "#a1b56c"
mime = "application/vnd.*"

[[filetype.rules]]
bold = true
fg = "#7cafc2"
mime = "inode/directory"

[[filetype.rules]]
fg = "#d8d8d8"
mime = "*"

[help]
[help.desc]
fg = "#d8d8d8"

[help.footer]
fg = "#d8d8d8"

[help.hovered]
bg = "#585858"
fg = "#d8d8d8"

[help.on]
fg = "#ba8baf"

[help.run]
fg = "#86c1b9"

[input]
[input.border]
fg = "#7cafc2"

[input.selected]
bg = "#585858"

[input.title]
fg = "#d8d8d8"

[input.value]
fg = "#d8d8d8"

[manager]
syntect_theme = "/nix/store/nqdv1d60xw69z944l99a0abaifsnx83d-untitled/base16-untitled.tmTheme"
[manager.border_style]
fg = "#b8b8b8"

[manager.cwd]
fg = "#86c1b9"

[manager.find_keyword]
bold = true
fg = "#a1b56c"

[manager.find_position]
fg = "#d8d8d8"

[manager.hovered]
bg = "#585858"
bold = true
fg = "#d8d8d8"

[manager.marker_copied]
bg = "#f7ca88"
fg = "#f7ca88"

[manager.marker_cut]
bg = "#ab4642"
fg = "#ab4642"

[manager.marker_selected]
bg = "#a1b56c"
fg = "#a1b56c"

[manager.preview_hovered]
bg = "#585858"
bold = true
fg = "#d8d8d8"

[manager.tab_active]
bg = "#7cafc2"
fg = "#000000"

[manager.tab_inactive]
bg = "#282828"
fg = "#d8d8d8"

[select]
[select.active]
fg = "#ba8baf"

[select.border]
fg = "#7cafc2"

[select.inactive]
fg = "#d8d8d8"

[status]
[status.mode_normal]
bg = "#7cafc2"
bold = true
fg = "#000000"

[status.mode_select]
bg = "#a1b56c"
bold = true
fg = "#000000"

[status.mode_unset]
bg = "#a16946"
bold = true
fg = "#000000"

[status.permissions_r]
fg = "#f7ca88"

[status.permissions_s]
fg = "#86c1b9"

[status.permissions_t]
fg = "#7cafc2"

[status.permissions_w]
fg = "#ab4642"

[status.permissions_x]
fg = "#a1b56c"

[status.progress_error]
bg = "#000000"
fg = "#ab4642"

[status.progress_label]
bg = "#000000"
fg = "#d8d8d8"

[status.progress_normal]
bg = "#000000"
fg = "#d8d8d8"

[status.separator_style]
bg = "#282828"
fg = "#282828"

[tasks]
[tasks.border]
fg = "#7cafc2"

[tasks.hovered]
bg = "#585858"
fg = "#d8d8d8"

[tasks.title]
fg = "#d8d8d8"

[which]
[which.cand]
fg = "#86c1b9"

[which.desc]
fg = "#d8d8d8"

[which.mask]
bg = "#383838"

[which.rest]
fg = "#a16946"

[which.separator_style]
fg = "#b8b8b8"
