[manager]
layout = [1, 3, 4]
linemode = "none"
show_hidden = false
show_symlink = false
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = true

[preview]
cache_dir = "/home/ben/.cache"
max_height = 900
max_width = 600
tab_size = 2
