# TODO Create a folder in `$HOME/windows` that points to C:\Users\Ben
# option -> meta.system.windows.mount_windows_folder = true;
# option -> meta.system.windows.mount_windows_user = "Ben";

# FIX: Overwriting settings generated by nix-anywhere and disko
# Specify that windows in fstab.
#fileSystems."/home/${config.meta.system.user}/win" = mkIf (cfg.disk !=null) {

# ADD Option for specifying windows drive?
#device = cfg.disk;
#fsType = "ntfs";
#options = [ "rw" ];
#};

{ config, lib, pkgs, ... }: 
with lib; with types;
let
    cfg = config.meta.system.windows;
in {
# ───────────────────────── Options ─────────────────────────
    options.meta.system.windows = {
        enable = mkEnableOption "Enable setup for Windows dual-boot or access.";
        disk = mkOption {
            type = nullOr str;
            default = null;
            description = "Specify the device for windows auto-mount";
        };
    };

# ───────────────────────── Configuration ─────────────────────────
    config = mkIf cfg.enable {

        time.hardwareClockInLocalTime = true;
        environment.systemPackages = with pkgs; [ ntfs3g ];
    };
}
