keys:
  - &users:
    - &asynthe age1d85xdv6am4sf3h7nc58m3pltjlf585vzcnu47cd4qm9m9fl73d0qp9kad5
  - &hosts:
      - &thinkpad age1hqnqf5898vxvffu3ajpjkxdjr3mujsr8x05kkmxqf5q5gjj2dfjqfcu68s
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *asynthe
        - *thinkpad
