{
    imports = [
        ./ai.nix
        ./fwupd.nix
        ./android.nix
        ./atuin.nix
        ./audio.nix
        ./bluetooth.nix
        ./boot.nix
        ./colord.nix
        ./controller.nix
        ./desktop.nix
        ./dev.nix
        ./docker.nix
        ./flatpak.nix
        ./fonts.nix
        ./fprintd.nix
        ./gaming.nix
        ./gimp.nix
        ./git.nix
        ./ime.nix
        ./impermanence.nix
        ./incus.nix
        ./intel.nix
        ./kiwix.nix
        ./kubernetes.nix
        ./minecraft.nix
        ./monero.nix
        ./mullvad-vpn.nix
        ./networking.nix
        ./nh.nix
        ./nvidia.nix
        ./nvim.nix
        ./paraview.nix
        ./password-store.nix
        ./qbittorrent.nix
        ./ssh.nix
        ./steam.nix
        ./syncthing.nix
        ./tailscale.nix
        ./tectonic.nix
        ./terraform.nix
        ./tpm.nix
        ./typst.nix
        ./user.nix
        ./vm.nix
        ./vscodium.nix
        ./wine.nix
        ./xdg.nix
    ];
}
