[completion.active]
bg = "#474849"
fg = "#ea5ce2"

[completion.border]
fg = "#03aeff"

[completion.inactive]
fg = "#c1c3c4"

[[filetype.rules]]
fg = "#42fff9"
mime = "image/*"

[[filetype.rules]]
fg = "#c9d364"
mime = "video/*"

[[filetype.rules]]
fg = "#c9d364"
mime = "audio/*"

[[filetype.rules]]
fg = "#ea5ce2"
mime = "application/zip"

[[filetype.rules]]
fg = "#ea5ce2"
mime = "application/gzip"

[[filetype.rules]]
fg = "#ea5ce2"
mime = "application/x-tar"

[[filetype.rules]]
fg = "#ea5ce2"
mime = "application/x-bzip"

[[filetype.rules]]
fg = "#ea5ce2"
mime = "application/x-bzip2"

[[filetype.rules]]
fg = "#ea5ce2"
mime = "application/x-7z-compressed"

[[filetype.rules]]
fg = "#ea5ce2"
mime = "application/x-rar"

[[filetype.rules]]
fg = "#ea5ce2"
mime = "application/xz"

[[filetype.rules]]
fg = "#06ea61"
mime = "application/doc"

[[filetype.rules]]
fg = "#06ea61"
mime = "application/pdf"

[[filetype.rules]]
fg = "#06ea61"
mime = "application/rtf"

[[filetype.rules]]
fg = "#06ea61"
mime = "application/vnd.*"

[[filetype.rules]]
bold = true
fg = "#03aeff"
mime = "inode/directory"

[[filetype.rules]]
fg = "#c1c3c4"
mime = "*"

[help.desc]
fg = "#c1c3c4"

[help.footer]
fg = "#c1c3c4"

[help.hovered]
bg = "#474849"
fg = "#c1c3c4"

[help.on]
fg = "#ea5ce2"

[help.run]
fg = "#42fff9"

[input.border]
fg = "#03aeff"

[input.selected]
bg = "#474849"

[input.title]
fg = "#c1c3c4"

[input.value]
fg = "#c1c3c4"

[manager]
syntect_theme = "/nix/store/7wv66dc3f1zxzlm1hmb17y8rvibl8bb1-untitled/base16-untitled.tmTheme"
[manager.border_style]
fg = "#a3a5a6"

[manager.cwd]
fg = "#42fff9"

[manager.find_keyword]
bold = true
fg = "#06ea61"

[manager.find_position]
fg = "#c1c3c4"

[manager.hovered]
bg = "#474849"
bold = true
fg = "#c1c3c4"

[manager.marker_copied]
bg = "#c9d364"
fg = "#c9d364"

[manager.marker_cut]
bg = "#b53b50"
fg = "#b53b50"

[manager.marker_selected]
bg = "#06ea61"
fg = "#06ea61"

[manager.preview_hovered]
bg = "#474849"
bold = true
fg = "#c1c3c4"

[manager.tab_active]
bg = "#03aeff"
fg = "#000000"

[manager.tab_inactive]
bg = "#1a1b1c"
fg = "#c1c3c4"

[select.active]
fg = "#ea5ce2"

[select.border]
fg = "#03aeff"

[select.inactive]
fg = "#c1c3c4"

[status.mode_normal]
bg = "#03aeff"
bold = true
fg = "#000000"

[status.mode_select]
bg = "#06ea61"
bold = true
fg = "#000000"

[status.mode_unset]
bg = "#cd6320"
bold = true
fg = "#000000"

[status.permissions_r]
fg = "#c9d364"

[status.permissions_s]
fg = "#42fff9"

[status.permissions_t]
fg = "#03aeff"

[status.permissions_w]
fg = "#b53b50"

[status.permissions_x]
fg = "#06ea61"

[status.progress_error]
bg = "#000000"
fg = "#b53b50"

[status.progress_label]
bg = "#000000"
fg = "#c1c3c4"

[status.progress_normal]
bg = "#000000"
fg = "#c1c3c4"

[status.separator_style]
bg = "#1a1b1c"
fg = "#1a1b1c"

[tasks.border]
fg = "#03aeff"

[tasks.hovered]
bg = "#474849"
fg = "#c1c3c4"

[tasks.title]
fg = "#c1c3c4"

[which.cand]
fg = "#42fff9"

[which.desc]
fg = "#c1c3c4"

[which.mask]
bg = "#28292a"

[which.rest]
fg = "#cd6320"

[which.separator_style]
fg = "#a3a5a6"
